"""add format but as list of string back in bundles table

Revision ID: 1092ee804c57
Revises: 15544a474b32
Create Date: 2024-01-07 13:47:22.757192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1092ee804c57'
down_revision: Union[str, None] = '15544a474b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundles', sa.Column('format', postgresql.ARRAY(sa.String(length=32)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundles', 'format')
    # ### end Alembic commands ###
