"""remove format in bundles table

Revision ID: 15544a474b32
Revises: 75f2b85a80b8
Create Date: 2024-01-07 13:45:47.259165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15544a474b32'
down_revision: Union[str, None] = '75f2b85a80b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundles', 'format')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundles', sa.Column('format', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
