"""keep fixing AmbiguousForeignKeysError for refers table

Revision ID: 15c04b222220
Revises: 96b3bdc537e1
Create Date: 2024-01-01 04:02:11.700918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c04b222220'
down_revision: Union[str, None] = '96b3bdc537e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
