"""add subscription_orders table

Revision ID: 596ed6a4ebed
Revises: dbd3adc05a36
Create Date: 2023-12-23 20:25:50.148344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '596ed6a4ebed'
down_revision: Union[str, None] = 'dbd3adc05a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_orders', sa.Column('before_next_billing_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('subscription_orders', 'next_billing_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_orders', sa.Column('next_billing_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('subscription_orders', 'before_next_billing_at')
    # ### end Alembic commands ###
