"""add order_id to purchases table

Revision ID: 6cf4c3eadc8b
Revises: 61e9937678b1
Create Date: 2023-12-24 15:47:35.578694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf4c3eadc8b'
down_revision: Union[str, None] = '61e9937678b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('order_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'purchases', 'subscription_orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'order_id')
    # ### end Alembic commands ###
