"""make coins field in UsersTable non-nullable

Revision ID: 7c109f50fa28
Revises: fbdfb3ed888d
Create Date: 2024-01-01 03:34:47.168568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c109f50fa28'
down_revision: Union[str, None] = 'fbdfb3ed888d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'coins',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'coins',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
