"""add PurchasesByCoinsTable and RefersTable

Revision ID: 7d36728cc32c
Revises: 77df078bedcc
Create Date: 2024-01-01 03:32:01.687478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d36728cc32c'
down_revision: Union[str, None] = '77df078bedcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases_by_coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coins_used', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bundle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_uid', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_uid', sa.String(length=32), nullable=True),
    sa.Column('referent_uid', sa.String(length=32), nullable=True),
    sa.Column('bundle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('referred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coins_gained', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['referent_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['referrer_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refers')
    op.drop_table('purchases_by_coins')
    # ### end Alembic commands ###
