"""add purchase_price to bundle table

Revision ID: 7dda3f0ebe33
Revises: bbcd44a8800d
Create Date: 2023-12-31 14:32:48.712239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dda3f0ebe33'
down_revision: Union[str, None] = 'bbcd44a8800d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundles', sa.Column('purchase_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundles', 'purchase_price')
    # ### end Alembic commands ###
