"""update nullable props for refers table

Revision ID: ad92599fba72
Revises: 15c04b222220
Create Date: 2024-01-01 19:41:09.421778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad92599fba72'
down_revision: Union[str, None] = '15c04b222220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refers', 'referrer_uid',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('refers', 'referent_uid',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refers', 'referent_uid',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('refers', 'referrer_uid',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
