"""add deleted to bundle table

Revision ID: bb821a99d5e7
Revises: 7dda3f0ebe33
Create Date: 2023-12-31 16:40:02.472272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb821a99d5e7'
down_revision: Union[str, None] = '7dda3f0ebe33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundles', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundles', 'deleted')
    # ### end Alembic commands ###
