"""add subscriptions/purchases/downloads table

Revision ID: bd5523468c84
Revises: cd9b009e130f
Create Date: 2023-12-22 15:33:51.222028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd5523468c84'
down_revision: Union[str, None] = 'cd9b009e130f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('before', sa.String(length=16), nullable=False),
    sa.Column('after', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_uid', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bundle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_uid', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bundle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_uid', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('subscription', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'next_billing_at')
    op.drop_column('users', 'subscription')
    op.drop_table('purchases')
    op.drop_table('downloads')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
