"""add bundles table

Revision ID: c7d2c269ff67
Revises: 413f4e702372
Create Date: 2023-12-15 21:36:27.451283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7d2c269ff67'
down_revision: Union[str, None] = '413f4e702372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('subtitle', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('carousel', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('creator_uid', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['creator_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bundles')
    # ### end Alembic commands ###
