"""add bookmarks table

Revision ID: cd9b009e130f
Revises: 7f1321067121
Create Date: 2023-12-22 05:56:20.279016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd9b009e130f'
down_revision: Union[str, None] = '7f1321067121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookmarked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bundle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_uid', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
