"""add subscription_orders table

Revision ID: dbd3adc05a36
Revises: bd5523468c84
Create Date: 2023-12-23 19:40:23.917572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd3adc05a36'
down_revision: Union[str, None] = 'bd5523468c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('before', sa.String(length=16), nullable=False),
    sa.Column('after', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_uid', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscriptions', sa.Column('order_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'subscription_orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'order_id')
    op.drop_table('subscription_orders')
    # ### end Alembic commands ###
