"""add coins field to UsersTable

Revision ID: fbdfb3ed888d
Revises: 7d36728cc32c
Create Date: 2024-01-01 03:33:45.834661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbdfb3ed888d'
down_revision: Union[str, None] = '7d36728cc32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coins')
    # ### end Alembic commands ###
